---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:14.2.1
  amd64: ghcr.io/hassio-addons/base/amd64:14.2.1
  armhf: ghcr.io/hassio-addons/base/armhf:14.2.1
  armv7: ghcr.io/hassio-addons/base/armv7:14.2.1
  i386: ghcr.io/hassio-addons/base/i386:14.2.1
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
