---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:14.3.2
  amd64: ghcr.io/hassio-addons/base/amd64:14.3.2
  armv7: ghcr.io/hassio-addons/base/armv7:14.3.2
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
