---
name: Tailscale
version: dev
slug: tailscale
description: Zero config VPN for building secure networks
url: https://github.com/hassio-addons/addon-tailscale
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 0
ingress_stream: true
startup: services
panel_icon: mdi:vpn
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
hassio_api: true
host_network: true
map:
  - share:rw
schema:
  tags: ["match(^tag:[a-zA-Z0-9]-?[a-zA-Z0-9]+$)?"]
  proxy_port: match(^(?:[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
