---
name: Tailscale
version: dev
slug: tailscale
description: Zero config VPN for building secure networks
url: https://github.com/hassio-addons/addon-tailscale
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 0
ingress_stream: true
startup: services
panel_icon: mdi:vpn
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
hassio_api: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
host_network: true
schema:
  tags: ["match(^tag:[a-zA-Z0-9]-?[a-zA-Z0-9]+$)?"]
