---
name: Tailscale
version: dev
slug: tailscale
description: Zero config VPN for building secure networks
url: https://github.com/hassio-addons/addon-tailscale
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 0
ingress_stream: true
startup: services
panel_icon: mdi:vpn
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
hassio_api: true
host_network: true
host_dbus: true
privileged:
  - NET_ADMIN
  - NET_RAW
devices:
  - /dev/net/tun
map:
  - share:rw
schema:
  accept_dns: bool?
  accept_routes: bool?
  advertise_exit_node: bool?
  funnel: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  login_server: url?
  proxy: bool?
  tags: ["match(^tag:[a-zA-Z0-9]-?[a-zA-Z0-9]+$)?"]
  taildrop: bool?
  userspace_networking: bool?
