#!/bin/bash
# DO NOT use #!/command/with-contenv bashio, because that won't set the environment variables

if [[ "$NM_DISPATCHER_ACTION" == "connectivity-change" ]]; then
  if [[ "$CONNECTIVITY_STATE" == "FULL" ]]; then
    if ! protect-subnet-routes; then
      # Better stop add-on than risking losing all network connections
      echo -n 1 > /run/s6-linux-init-container-results/exitcode
      exec /run/s6/basedir/bin/halt
    fi
  else # UNKNOWN, NONE, PORTAL, LIMITED
    unprotect-subnet-routes
  fi
fi
